### ISSUE TITLE
Support for "should.throw()"

### ISSUE THREAD

**Issue by yanickrochon** [blakeembrey/co-mocha#7]
Right now, I am testing `.should.throw()` with some ugly hacks. It would be nice to have this support with `co-mocha`.

Something like

``` javascript
(yield function * () { /* async code */ }).should.throw();
```

**Comment by wmertens** [comment]
I solved it for the Promise case with

```es6
    const failP = p => p.then(() => Promise.reject("should fail"), () => true)

	it('should fail', function *() {
		yield failP(Promise.reject())
	})
```

I wish I could make something similar for the whole generator function.

**Comment by MajorBreakfast** [comment]
@wmertens That code looks weird. I recommend using babel and `async function () {}` nowadays.

```JSON
{
  "scripts": {
    "test": "babel-node run-tests.js"
  },
  "devDependencies": {
    "babel-cli": "^6.3.17",
    "babel-plugin-transform-async-to-generator": "^6.3.13"
  },
  "babel": {
    "plugins": ["transform-async-to-generator"]
  }
}
```

Then your tests look like this:
```JS
it('does something', async function () {
  await fs.mkdir('a')
  await fs.createFile('a/b', 'Hello Wolrd!')
})
```

You run it with `npm test` (as always).

**Comment by blakeembrey** [comment]
:+1: for `async`, since Mocha supports promises anyway. @wmertens, what are you trying to do with that function?

**Comment by wmertens** [comment]
Actually, yeah, await is nicer than yield, but what I want to express is that the promise should fail without having to do the try/catch construct…

**Comment by MajorBreakfast** [comment]
Take a look at `chai-as-promised` (https://github.com/domenic/chai-as-promised/). That's what you're searching for.

It the looks like this:
```JS
await yourOperationThatFails().should.be.rejected
```

**Comment by yanickrochon** [comment]
Should.js implements [this](http://shouldjs.github.io/#assertion-rejected). Now that I am moving away from `yield` into the promise land (hehe) I can test my asynchronous failures as

```
it('should fail', function () {
  return new Promise(function (resolve, reject) {
    setTimeout(function () {
      reject(new Error('foo'));
    }, 200);
  }).should.be.rejectedWith('foo');
});
```

Also, I no longer use `co-mocha` :) as `mocha` handles Promises natively as the above example demonstrates.

**Comment by wmertens** [comment]
I am just getting started with generators and eyeing koajs, so I wanted to try out generators and wanted to test a promise rejection without relying on the fact that it is a promise.

I missed the `should.Throw` implementation above, I wanted to do the same with a helper function like `failP` for generators but couldn't make it work, yielding the original generator function doesn't work for me.

However, I right now don't have a use case that cannot be solved by Promises, so I'll just keep using those for now. In koajs there is also discussion about async/await (https://github.com/koajs/koa/issues/339), seems like the consensus is that co+yield is a bit of a hack to achieve async/await, and I'm inclined to agree.

PS: Not really related, but very awesome: check out https://github.com/power-assert-js/babel-plugin-espower, it shows all the values in a failing assertion. Just spreading the word, since you're depending on babel anyways.

**Comment by MajorBreakfast** [comment]
@wmertens `power-assert` seems really nice!
